/** Static code-mode capability contract. No kernel/runtime imports belong in this module. */
export function canAddCodeMode(tools: ReadonlyArray<{ name: string }>): boolean {
  return tools.length > 0 && !tools.some(tool => tool.name === 'exec');
}

export const CODE_MODE_INSTRUCTIONS = `Code mode: use exec with a code string for bounded tool composition and filtering. Inside JavaScript, call tools by their existing names and arguments. Results are normal MCP objects; inspect content, structuredContent and isError. Only text(...) and image(...) emit data to the model. Given requests you define using this connector's listed tool schemas:
const results = await Promise.all(requests.map(({name, args}) => tools[name](args)));
text(results.map((result, index) => ({index, isError: result.isError ?? false, content: result.content})));
Keep emitted text within 40,000 UTF-8 bytes total. For large read batches, request smaller max_bytes or line ranges, filter the returned content, or use read directly. Forward images with image(...), not text(result); base64 serialized as text consumes the text limit. An oversized text emission returns an explicitly truncated preview and stops the script; inspect already dispatched calls before retrying.
Keep independent calls parallel only when their operations do not conflict; await mutations before dependent work. Use image(result.content.find(item => item.type === "image")) to forward a native image explicitly. A script without text/image returns no intermediate data. All nested calls still check live permissions and retain the caller’s proven identity, or remain Unattributed when allowed. Each child is individually recorded. Chat-owned operations such as agents and update_plan still require exact identity. New user instructions and worker inbox messages arrive with the outer result, outside filtering. Call finish/lifecycle signals directly. Use individual tools for simple calls, native file arguments, or when a result needs fresh model judgment. No persistent script state or code-mode wait tool; long-running tools retain their existing continuation contracts.`;
